services:
  - type: web
    name: crypto-fintech
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-fintech-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: crypto-fintech-db
    databaseName: crypto_fintech
    user: crypto_user
